[preferences]
assignment_name = "Assignment 2"
description = "Divide two numbers."

[tests.First]
input = "1 2"
output = "0.5"
public = true

[tests.Second]
input = "24 48"
output = "0.5"
public = true
