[preferences]
name = "Assignment 1"
description = "Reverse the input."

[tests.SimpleFirst]
input_file = "test1.in"
output = "oofamoodaks"

[tests.SimpleSecond]
input = "smay"
output_file = "test2.out"

[tests.WrongPublic]
input = "smay"
output = "Intentionally Wrong"
public = true

[tests.WrongPrivate]
input = "wubba wubba"
output = "Intentionally Wrong"