[preferences]
assignment_name = "Assignment 1"
description = "Divide two numbers."
timeout = 2

[tests.First]
input = "smay"
output = "yams"
public = true

[tests.Second]
input = "smelly"
output = "yllems"

[tests.Third]
input = "smelly3"
output = "3yllems"
